//Bloco de ConfiguraÃ§Ãµes do aplicativo inicio
var cliente ="";
var empresa='3';
var URLAPP = 'http://sistema.entregapp.com.br/';
var salt ="jmgl33mg1221kjgruyky232ho2l3437mhljio90hueemmgjktjmmmgko2tut35ymmmh221eenngl4y73kkkj";
var filialPadrao="7";
var prodId1='';
var prodId2='';
var telefonePadrao="tel:2792-6699";
var prodId1='';
var prodId2='';
var prodTamanho="";
var itenObs="";
var bebidas=null;
var pagueGanhe=null;
var itemPagueGanheId=null;
var itemPagueGanheNome=null;
var itemBebidaId =null;
var itemBebidaNome  = null;
